jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        LesAutres\SiteBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: LesAutresSiteBundle:User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$
            security: false

        secured_area:
            pattern:    ^/admin
            anonymous: ~
            http_basic:
                realm: "Espace Administrateur"
                provider: user_db

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
