homepage:
    pattern:  /
    defaults: { _controller: LesAutresSiteBundle:Browse:index }

admin:
    pattern:  /admin
    defaults: { _controller: LesAutresSiteBundle:Admin:index }

contact_form:
    pattern:  /nous-contacter
    defaults: { _controller: LesAutresSiteBundle:Contact:form }

contact_confirm:
    pattern:  /nous-contacter/confirmation
    defaults: { _controller: LesAutresSiteBundle:Contact:confirm }

sitemap:
    pattern:  /sitemap.xml
    defaults: { _controller: LesAutresSiteBundle:Default:sitemap }

page:
    pattern:  /{slug}
    defaults: { _controller: LesAutresSiteBundle:Browse:page }

show:
    pattern:  /spectacle/{slug}
    defaults: { _controller: LesAutresSiteBundle:Browse:show }

feed_events:
    pattern:  /flux/evenements/{type}
    defaults: { _controller: LesAutresSiteBundle:Feed:events }
