homepage:
    pattern:  /
    defaults: { _controller: LesAutresSiteBundle:Browse:index }

admin:
    pattern:  /admin
    defaults: { _controller: LesAutresSiteBundle:Admin:index }

page:
    pattern:  /{slug}
    defaults: { _controller: LesAutresSiteBundle:Browse:page }

show:
    pattern:  /spectacle/{slug}
    defaults: { _controller: LesAutresSiteBundle:Browse:show }

#date:
#    pattern:  /date/{day}/{month}/{year}
#    defaults: { _controller: LesAutresSiteBundle:Browse:date }
