homepage:
    pattern:  /
    defaults: { _controller: LesAutresSiteBundle:Default:index }

admin:
    pattern:  /admin
    defaults: { _controller: LesAutresSiteBundle:Admin:index }

page:
    pattern:  /{slug}
    defaults: { _controller: LesAutresSiteBundle:Default:page }

show:
    pattern:  /spectacle/{slug}
    defaults: { _controller: LesAutresSiteBundle:Default:show }

date:
    pattern:  /date/{day}/{month}/{year}
    defaults: { _controller: LesAutresSiteBundle:Default:date }
