<?php

namespace LesAutres\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function getLatestEvent()
    {
        $query = $this->createQueryBuilder('e')
            ->orderBy('e.createdAt', 'DESC')
            ->setMaxResults(1)
            ->getQuery();
        
        try {
            $event = $query->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            $event = null;
        }
        
        return $event;
    }
}
