<?php

namespace LesAutres\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowRepository extends EntityRepository
{
}
