<?php

namespace LesAutres\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowRepository extends EntityRepository
{
    public function getShowsForPage(Page $page)
    {
        $query = $this->createQueryBuilder('s')
            ->where('s.page = :page')
            ->setParameter('page', $page)
            ->orderBy('s.createdAt', 'DESC')
            ->getQuery()
        ;

        return $query->getResult();
    }
}
